receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14268"
  zipkin:
  otlp:
    protocols:
      grpc: # on port 55680
      http: # on port 55681
processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 100
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": '{{ with secret "kv/honeycomb" }}{{ .Data.data.api_key }}{{ end }}'
extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 165
service:
  extensions: [ health_check, pprof, zpages, memory_ballast ]
  pipelines:
    traces:
      receivers: [ jaeger, zipkin, otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp ]
