// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package desec

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/desec/desec/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DomainKey struct {
	Dnskey  string   `pulumi:"dnskey"`
	Ds      []string `pulumi:"ds"`
	Flags   float64  `pulumi:"flags"`
	Keytype string   `pulumi:"keytype"`
}

// DomainKeyInput is an input type that accepts DomainKeyArgs and DomainKeyOutput values.
// You can construct a concrete instance of `DomainKeyInput` via:
//
//	DomainKeyArgs{...}
type DomainKeyInput interface {
	pulumi.Input

	ToDomainKeyOutput() DomainKeyOutput
	ToDomainKeyOutputWithContext(context.Context) DomainKeyOutput
}

type DomainKeyArgs struct {
	Dnskey  pulumi.StringInput      `pulumi:"dnskey"`
	Ds      pulumi.StringArrayInput `pulumi:"ds"`
	Flags   pulumi.Float64Input     `pulumi:"flags"`
	Keytype pulumi.StringInput      `pulumi:"keytype"`
}

func (DomainKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainKey)(nil)).Elem()
}

func (i DomainKeyArgs) ToDomainKeyOutput() DomainKeyOutput {
	return i.ToDomainKeyOutputWithContext(context.Background())
}

func (i DomainKeyArgs) ToDomainKeyOutputWithContext(ctx context.Context) DomainKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainKeyOutput)
}

// DomainKeyArrayInput is an input type that accepts DomainKeyArray and DomainKeyArrayOutput values.
// You can construct a concrete instance of `DomainKeyArrayInput` via:
//
//	DomainKeyArray{ DomainKeyArgs{...} }
type DomainKeyArrayInput interface {
	pulumi.Input

	ToDomainKeyArrayOutput() DomainKeyArrayOutput
	ToDomainKeyArrayOutputWithContext(context.Context) DomainKeyArrayOutput
}

type DomainKeyArray []DomainKeyInput

func (DomainKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DomainKey)(nil)).Elem()
}

func (i DomainKeyArray) ToDomainKeyArrayOutput() DomainKeyArrayOutput {
	return i.ToDomainKeyArrayOutputWithContext(context.Background())
}

func (i DomainKeyArray) ToDomainKeyArrayOutputWithContext(ctx context.Context) DomainKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainKeyArrayOutput)
}

type DomainKeyOutput struct{ *pulumi.OutputState }

func (DomainKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainKey)(nil)).Elem()
}

func (o DomainKeyOutput) ToDomainKeyOutput() DomainKeyOutput {
	return o
}

func (o DomainKeyOutput) ToDomainKeyOutputWithContext(ctx context.Context) DomainKeyOutput {
	return o
}

func (o DomainKeyOutput) Dnskey() pulumi.StringOutput {
	return o.ApplyT(func(v DomainKey) string { return v.Dnskey }).(pulumi.StringOutput)
}

func (o DomainKeyOutput) Ds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainKey) []string { return v.Ds }).(pulumi.StringArrayOutput)
}

func (o DomainKeyOutput) Flags() pulumi.Float64Output {
	return o.ApplyT(func(v DomainKey) float64 { return v.Flags }).(pulumi.Float64Output)
}

func (o DomainKeyOutput) Keytype() pulumi.StringOutput {
	return o.ApplyT(func(v DomainKey) string { return v.Keytype }).(pulumi.StringOutput)
}

type DomainKeyArrayOutput struct{ *pulumi.OutputState }

func (DomainKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DomainKey)(nil)).Elem()
}

func (o DomainKeyArrayOutput) ToDomainKeyArrayOutput() DomainKeyArrayOutput {
	return o
}

func (o DomainKeyArrayOutput) ToDomainKeyArrayOutputWithContext(ctx context.Context) DomainKeyArrayOutput {
	return o
}

func (o DomainKeyArrayOutput) Index(i pulumi.IntInput) DomainKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DomainKey {
		return vs[0].([]DomainKey)[vs[1].(int)]
	}).(DomainKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainKeyInput)(nil)).Elem(), DomainKeyArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainKeyArrayInput)(nil)).Elem(), DomainKeyArray{})
	pulumi.RegisterOutputType(DomainKeyOutput{})
	pulumi.RegisterOutputType(DomainKeyArrayOutput{})
}
