{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Cluster control plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hashistack memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (node_name) (process_resident_memory_bytes{job=~\"(consul-agent|nomad-agent|vault)\",node_name=~\"megaera|tisiphone|alecto\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node available memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_MemFree_bytes{node_name=~\"megaera|tisiphone|alecto\"} + node_memory_Cached_bytes{node_name=~\"megaera|tisiphone|alecto\"} + node_memory_Buffers_bytes{node_name=~\"megaera|tisiphone|alecto\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Ethernet egress rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (node_name) (irate(node_network_transmit_bytes_total{device=~\"^(eth0|end0|ens18)$\",node_name=~\"megaera|tisiphone|alecto\"}[5m])*8)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Vault leases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "max(vault_expire_num_leases)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cluster nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Hashistack memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (node_name) (process_resident_memory_bytes{job=~\"consul-agent|nomad-agent\",node_name!~\"megaera|tisiphone|alecto\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node available memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_MemFree_bytes{node_name=~\"arges|brontes|steropes|helios\"} + node_memory_Cached_bytes{node_name=~\"arges|brontes|steropes|helios\"} + node_memory_Buffers_bytes{node_name=~\"arges|brontes|steropes|helios\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Ethernet egress rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (node_name) (irate(node_network_transmit_bytes_total{device=~\"^(eth0|end0|ens18)$\",node_name=~\"arges|brontes|steropes|helios\"}[5m])*8)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Raspberry Pi temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (node_name) (node_hwmon_temp_celsius{node_name=~\"^(arges|brontes|steropes)$\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Raspberry Pi fan state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_cooling_device_max_state{node_name=~\"arges|brontes|steropes\"}",
     "legendFormat": "max: {{node_name}}"
    },
    {
     "expr": "node_cooling_device_cur_state{node_name=~\"arges|brontes|steropes\"}",
     "legendFormat": "cur: {{node_name}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "UPS battery health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(network_ups_tools_battery_charge)"
    }
   ]
  }
 ]
}