.snippets:
  setup_devenv:
    - . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  nixos_changes:
    - .gitlab-ci.yml
    - default.nix
    - hive.nix
    - apps/**/*
    - home/**/*
    - hosts/**/*
    - modules/**/*
    - npins/*
    - packages/**/*
    - secrets/**/*
    - services/**/*
  tofu_changes:
    - .gitlab-ci.yml
    - apps/**/*
    - modules/apps/**/*
    - npins/*
    - services/*/service.nix
    - services/*/service/**/*
    - terraform/**/*
stages:
  - check
  - deploy
variables:
  CONSUL_HTTP_ADDR: "consul.service.consul:8500"
  VAULT_ADDR: "http://vault.service.consul:8200"
build nixos hosts:
  tags: [nix-shell, "x86_64"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.snippets, nixos_changes]
  stage: check
  needs: []
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://vault.service.consul:8200
  script:
    - nix run -f . ci-attic-login
    - nix run -f . ci-build
deploy nixos hosts:
  tags: [nix-shell, "x86_64"]
  rules:
    - when: manual
  stage: deploy
  needs: []
  environment:
    name: production
  resource_group: production/nixos
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://vault.service.consul:8200
  # before_script: !reference [.snippets, setup_devenv]
  script:
    - nix run -f . ci-attic-login
    - nix run -f . ci-deploy
deploy nixos hosts (reboot):
  tags: [nix-shell, "x86_64"]
  rules:
    - when: manual
  stage: deploy
  needs: []
  environment:
    name: production
  resource_group: production/nixos
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://vault.service.consul:8200
  script:
    - nix run -f . ci-attic-login
    - nix run -f . ci-deploy-reboot
build tofu changes:
  tags: [nix, x86_64]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: !reference [.snippets, tofu_changes]
  stage: check
  needs: []
  variables:
    TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE: "yes"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://vault.service.consul:8200
  before_script: !reference [.snippets, setup_devenv]
  script:
    - nix run -f . ci-terraform-plan
apply terranix changes:
  tags: [nix, x86_64]
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
      changes: !reference [.snippets, tofu_changes]
  stage: deploy
  needs: []
  environment:
    name: production
  resource_group: production/nomad
  variables:
    TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE: "yes"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://vault.service.consul:8200
  before_script: !reference [.snippets, setup_devenv]
  script:
    - nix run -f . ci-terraform-apply
check for flake updates:
  tags: [nix-shell]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: check
  # before_script: !reference [.snippets, setup_devenv]
  script:
    - nix run -f . ci-update-pins
