update hosts:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    UPDATE_NIX: "true"
    # can't find a way to get this in the API, so we put this variable here so
    # we can pull it from the variables endpoint to trace back to this pipeline.
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    project: mjm/homelab-infra
    strategy: depend
