# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: let
  mkSubvol = name: opts:
    {
      device = "/dev/disk/by-uuid/a5f6fd18-f9e4-4fe3-9e62-62f054ee80ee";
      fsType = "btrfs";
      options = ["subvol=${name}" "compress=zstd" "noatime"];
    }
    // opts;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = mkSubvol "root" {};
  fileSystems."/home" = mkSubvol "home" {};
  fileSystems."/nix" = mkSubvol "nix" {neededForBoot = true;};
  fileSystems."/persist" = mkSubvol "persist" {neededForBoot = true;};
  fileSystems."/var/log" = mkSubvol "log" {neededForBoot = true;};
  fileSystems."/var/lib/libvirt" = mkSubvol "libvirt" {};
  fileSystems."/var/lib/fprint" = mkSubvol "fprint" {};
  fileSystems."/var/lib/NetworkManager" = mkSubvol "networkmanager" {};
  fileSystems."/var/lib/iwd" = mkSubvol "iwd" {};

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B0EC-18F2";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/79dd84d8-e448-41fe-a638-91e898382be5";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
