groups:
  - name: ups_alerts
    rules:
      - alert: NoUPSData
        expr: absent(network_ups_tools_ups_status)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: UPS metric data is missing
          description: >
            No UPS metrics are being scraped. Check if the nut-exporter is running and is able to connect to NUT on the Synology.

            https://nomad.home.mattmoriarity.com/ui/jobs/nut https://consul.home.mattmoriarity.com/ui/dc1/services/nut/instances

      - alert: UPSDischarging
        expr: network_ups_tools_ups_status{flag="DISCHRG"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: UPS battery is discharging
          description: >
            The UPS battery is currently discharging. If power does not return, it will likely run out of battery in 30-40 minutes.
