// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/desec/desec/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The API token for operations.
func GetApiToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "desec:apiToken")
}
func GetApiUri(ctx *pulumi.Context) string {
	return config.Get(ctx, "desec:apiUri")
}

// The max number of retries when sending an API request.
func GetRetryMax(ctx *pulumi.Context) float64 {
	return config.GetFloat64(ctx, "desec:retryMax")
}
