{
  imports = [
    ./actual
    ./atticd
    ./atuin
    ./authelia
    ./consul
    ./garage
    ./gitlab
    ./gitlab-runner
    ./grafana
    ./home-assistant
    ./icloudpd
    ./ingress
    ./ipv4-proxy
    ./launchpad
    ./libvirtd
    ./linkding
    ./matrix-server
    ./media-server
    ./miniflux
    ./netbox
    ./nut
    ./otel-collector
    ./paperless
    ./postgresql
    ./prometheus
    ./remote-builder
    ./tailscale
    ./vault
    ./vaultwarden
  ];
}
