apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.0.2.41:9090
    isDefault: true
    version: 2
    editable: false
    uid: prom_homelab
  - name: Loki
    type: loki
    access: proxy
    url: http://loki.service.consul:3100
    version: 2
    editable: false
    jsonData:
      maxLines: 1000
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://10.0.2.41:9093
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
